### PR TITLE
FLB#17 | synchronise production catches without weakening offline saves

### LINKED ISSUE #17: [Feature] Synchronise production Catches after reconnect
### Context

Production Catch recording is now offline-first.

The preceding work establishes the foundations that #17 must build on:

- **#14** introduced the real production `Catch` flow:
  - client-generated stable `CatchId`
  - one Catch → many `CatchPhotograph`
  - stable client-generated `CatchPhotographId`
  - atomic IndexedDB persistence
  - multiple photographs
  - local Catch list
  - Catch save never requires network access
- **#15** added optional captured location to the production Catch.
  - location is persisted locally with the Catch
  - failure/denial/timeout never blocks save
- **#16** establishes Catch **location privacy/visibility**.
  - exact coordinates may be persisted by the server
  - exposure to viewers is privacy-shaped separately
- **#7** proved duplicate-safe metadata synchronisation using `TestCatch`.
- **#11** proved offline photograph persistence and later R2 upload using `TestCatch`.

`TestCatch` was the proving ground.

#17 promotes the proven synchronisation behaviour into the **real production Catch flow**.

Do **not** build a second synchronisation architecture.

---

### Goal

Synchronise production Catches safely after connectivity becomes available while preserving the fundamental offline-first promise:

> Recording a Catch finishes when it is safely stored on the device. Synchronisation happens afterwards.

A production Catch must be able to move through a clear local synchronisation lifecycle:

```text
Saved locally
→ Waiting to synchronise
→ Synchronising
→ Synchronised
```

and, when something fails:

```text
Synchronising
→ Failed
→ Retry
→ Synchronising
→ Synchronised
```

Catch metadata, optional location and all photographs must eventually reach the server without:

- creating duplicate Catches
- creating duplicate photograph records
- creating duplicate R2 objects
- losing captured location
- changing ownership
- blocking waterside Catch recording
- losing locally persisted data after app close/reopen

The user must be able to see synchronisation state and manually retry failed work.

---

### Requirement references

- `docs/Requirements.md` — #2.2 Offline First
- `docs/Requirements.md` — Offline Synchronisation
- `docs/Requirements.md` — Initial User Journey / Recreational Angler
- merged #14 — production offline Catch
- merged #15 — production optional location
- merged #16 — location privacy
- #7 — TestCatch duplicate-safe synchronisation proof
- #11 — TestCatch photograph upload proof

---

## Core principle — Save and Sync are separate

The #14 waterside flow must remain unchanged.

```text
Take/select photographs
→ review
→ Save
→ Catch saved locally
→ angler can continue fishing
```

`Save` MUST NOT:

- call the Catch API
- wait for connectivity
- wait for metadata synchronisation
- wait for R2 upload
- wait for photograph synchronisation
- show failure merely because the server is unavailable

A successful waterside Save means:

> This Catch is safely persisted on this device.

Synchronisation is a later/background concern.

---

## Production Catch only

#17 must synchronise the real production:

- `Catch`
- `CatchPhotograph`
- optional `CatchLocation`

Do not extend `TestCatch` as the product implementation.

Before changing code, inventory the existing TestCatch synchronisation/photo-upload implementation and classify each part:

- **REUSE**
- **REFACTOR / GENERALISE**
- **TEMPORARILY KEEP**
- **REMOVE**

Prefer promoting/generalising proven mechanisms over copying them.

End state:

> Production Catch is the active synchronised product path.

TestCatch must not remain a parallel user-facing catch system.

---

# Synchronisation model

## Catch metadata and photographs are separate sync operations

A Catch has two kinds of server work:

### 1. Catch metadata

Includes the production Catch state supported at the time of #17, including:

- stable `CatchId`
- `CaughtOn`
- optional captured Location
- Location accuracy/source/captured timestamp
- Location visibility/privacy metadata
- other production Catch metadata already implemented

Location is part of Catch metadata.

Do NOT implement a separate independent “location sync” operation.

### 2. Catch photographs

Each `CatchPhotograph` has:

- stable client-generated `PhotographId`
- `CatchId`
- bytes/blob
- content type
- ordering metadata where present

Each photograph must be synchronisable/retryable independently.

---

# Synchronisation ordering

Use this production sequence:

```text
1. Ensure Catch metadata exists on server
2. Synchronise each photograph
3. Mark Catch fully Synchronised only when metadata + every required photograph succeeded
```

Photograph work must not run against a server Catch that cannot yet be established.

If metadata synchronisation fails:

```text
Catch = Failed
Photographs remain local
No photograph data is lost
```

If metadata succeeds but one photograph fails:

```text
Catch server record exists
Location remains on server
Successful photographs remain successful
Failed photograph remains retryable
Overall Catch = Failed
```

Retry only the work that still requires synchronisation.

Do not deliberately repeat already-successful uploads unless the operation is itself proven idempotent and retrying is necessary.

---

# Stable client identity / idempotency

The stable IDs created by #14 are the idempotency foundation.

## Catch

The server must treat the client-generated `CatchId` as the identity of that Catch.

Retrying metadata synchronisation for the same:

```text
UserId + CatchId
```

must update/reuse the existing Catch, not create another Catch.

Do not replace the client `CatchId` with a new server-generated identity during retry.

## CatchPhotograph

The server/upload path must treat the stable client-generated `CatchPhotographId` as the identity of the photograph.

Retrying the same photograph must not create:

- a second photograph database row
- another logical photograph
- a new random R2 object for the same photograph

Use a deterministic object identity/key based on trusted ownership + stable Catch/Photograph identity, following existing R2 conventions.

Do not use:

- retry count
- timestamp of retry
- random GUID generated during upload
- filename alone

as photograph identity.

---

# Ownership and authentication

All production synchronisation is authenticated.

Ownership is always derived from:

```text
validated Cognito token
→ internal UserId
→ ICurrentUser
```

Do NOT trust client-supplied:

- UserId
- OwnerUserId
- ActorUserId
- email
- capability list

The client may send the stable `CatchId`, photograph IDs and Catch data.

The server decides which internal User owns the synchronised data.

A client must not be able to synchronise a Catch into another user's account by changing a request property.

Follow the security pattern established by #9 / #13.

---

# Location and #16 privacy

Production synchronisation MUST include the owner's **exact captured location** when the Catch has one.

That is correct.

Privacy does NOT mean the server should only receive approximate coordinates.

The server needs the original precise location so:

- the owner retains their exact location
- future visibility changes remain possible
- approximate/public exposure can be derived correctly

The sync payload therefore may contain the owner's exact location over the authenticated connection.

It must also persist:

- visibility
- source
- accuracy
- captured timestamp
- consent/version metadata already defined

#16 controls what a different viewer receives from server read APIs.

#17 must NOT bypass or weaken #16 viewer-response shaping.

Do not:

- make location Public during sync
- infer visibility from connectivity
- infer visibility from upload
- strip Private location from the server record
- expose exact private coordinates through a generic sync response

---

# Location must never be dropped by photograph retry

This is a mandatory regression case.

Scenario:

```text
Catch metadata + location sync succeeds
Photograph A upload succeeds
Photograph B upload fails
```

Later:

```text
Retry Photograph B
```

must NOT:

- overwrite Catch metadata with a partial object
- null Location
- change LocationVisibility
- modify captured coordinates
- recreate the Catch

Photograph retry is photograph work.

Do not use a partial Catch payload that inadvertently erases already-persisted metadata.

Add explicit automated coverage.

---

# Synchronisation states

Production Catch local state must support at least:

```text
SavedLocally
WaitingToSynchronise
Synchronising
Synchronised
Failed
```

Use stable machine-readable values.

User-facing EN labels:

- Saved on this device
- Waiting to synchronise
- Synchronising
- Synchronised
- Synchronisation failed

Provide French equivalents using normal localisation resources.

Do not store localised strings in IndexedDB.

---

# Meaning of each state

## SavedLocally

The Catch is safely stored on the device.

It has not yet entered an active network synchronisation attempt.

A newly recorded offline Catch initially satisfies this state.

It may transition quickly to WaitingToSynchronise depending on the orchestrator, but the user-facing distinction must remain understandable.

## WaitingToSynchronise

Network/server work is outstanding and no attempt is currently executing.

Examples:

- offline
- waiting for connectivity
- queued after app startup

## Synchronising

A synchronisation attempt for this Catch is currently running.

Do not leave a Catch permanently in this state after browser/app termination.

On restart, stale/incomplete Synchronising work must become retryable again.

## Synchronised

All required production Catch work succeeded:

- metadata persisted
- location persisted where present
- every required photograph synchronised/uploaded

Only then is the Catch fully Synchronised.

## Failed

At least one required sync operation failed.

The Catch remains fully usable locally.

Failure must not delete:

- Catch metadata
- photographs
- photograph bytes
- location
- stable IDs

The user may retry.

---

# Photograph-level state

Catch-level state alone is not sufficient internally.

Each photograph needs enough local synchronisation state to determine whether it still requires work.

At minimum the implementation must distinguish conceptually:

```text
Pending
Synchronising
Synchronised
Failed
```

Exact naming may follow existing conventions.

This allows:

```text
Photo A = Synchronised
Photo B = Failed
Photo C = Synchronised
```

without re-uploading everything unnecessarily.

Do not expose a complicated photograph-level status UI in #17 unless it improves the Catch experience.

The user primarily sees Catch-level state.

---

# Deriving overall Catch state

Overall Catch state must be deterministic.

Conceptually:

```text
if active sync work:
    Synchronising

else if metadata failed OR any required photograph failed:
    Failed

else if metadata synced AND every required photograph synced:
    Synchronised

else if network work remains:
    WaitingToSynchronise

else:
    SavedLocally
```

Do not allow:

```text
Catch = Synchronised
Photo B = Failed
```

That state is invalid.

---

# Automatic synchronisation triggers

Do not rely solely on one browser `online` event.

A pending Catch must have opportunities to synchronise when:

- connectivity returns
- the application starts while online
- the application resumes/re-enters a usable state where current architecture supports it
- the user manually retries

Use the smallest reliable browser/PWA orchestration appropriate to the current architecture.

Do not introduce complex background-sync infrastructure that is poorly supported across iOS browsers solely for #17.

The app must still work correctly if true background execution is unavailable.

The reliable minimum is:

```text
Catch persists locally
→ app is opened/resumed online
→ pending sync is attempted
```

Do not promise synchronization while the PWA is completely terminated unless the chosen browser technology genuinely guarantees it.

---

# Connectivity detection is a hint, not proof

`navigator.onLine` / browser online state does not prove:

- API reachable
- DNS works
- authentication works
- R2 works

Use connectivity state as a trigger/hint only.

Actual HTTP success determines whether synchronisation succeeded.

Do not mark a Catch Synchronised merely because the device says it is online.

---

# Authentication/session expiry

A Catch may have been saved while the user had previously authenticated but the OIDC/API session may no longer be usable when sync runs.

If synchronisation cannot proceed because authentication is unavailable/expired:

- keep Catch locally
- keep all photographs
- do not delete anything
- do not mark it Synchronised
- make it retryable after authentication returns

Do not silently redirect from a background sync operation in a way that loses state.

Use existing authentication/client conventions.

Do not implement a new token-refresh architecture unless genuinely required.

---

# Retry

The user must have an explicit manual retry option for Failed Catches.

Retry should:

```text
Failed
→ Synchronising
→ Synchronised
```

when successful.

Or:

```text
Failed
→ Synchronising
→ Failed
```

if the problem remains.

Retry must be idempotent.

The user must be able to tap Retry multiple times without creating duplicates.

---

# Retry granularity

The orchestrator should retry only outstanding work where state is known.

Example:

```text
metadata = Synced
photo A = Synced
photo B = Failed
photo C = Synced
```

Retry should target Photo B.

Do not intentionally recreate the metadata record or re-upload A/C merely because B failed.

If an operation must be repeated for recovery, it must remain idempotent.

---

# Concurrent sync protection

Do not allow two simultaneous sync attempts for the same Catch from the same running client to race each other.

Examples:

```text
online event
+
startup scan
+
manual Retry
```

must not start three independent uploads for the same Catch.

Use a per-Catch in-flight guard / orchestration mechanism appropriate to the architecture.

This is an in-process coordination concern.

Do not introduce distributed locking.

Server operations must remain idempotent regardless.

---

# Multiple pending Catches

Synchronisation must support more than one pending Catch.

Do not build an implementation that only knows about “the current Catch”.

Example:

```text
Catch A saved offline
Catch B saved offline
Catch C saved offline
```

Reconnect:

all three eventually attempt synchronisation.

Failure of Catch B must not prevent A or C from completing.

Avoid one failed Catch poisoning the entire queue.

Use controlled sequencing/concurrency appropriate to a mobile PWA; do not fire unbounded photograph uploads.

---

# App close / reopen

Sync state itself must survive browser/PWA close and reopen.

Scenario:

```text
Catch stored offline
→ app closed
→ app reopened online
```

The Catch must still be present and eligible for sync.

Scenario:

```text
metadata synced
→ one photo failed
→ app closed
→ app reopened
```

The client must know:

- metadata is already synced
- which photograph still needs work
- which photographs already succeeded

and resume/retry correctly.

Do not reset every Catch back to an unknown state on startup.

---

# Crash/interruption recovery

If the application closes/crashes while local state says:

```text
Synchronising
```

do not assume the operation succeeded.

On the next startup, reconcile it into a retryable state.

Because server operations are idempotent, retrying after an uncertain interruption must remain safe.

Do not permanently strand Catches in Synchronising.

---

# Local data retention

Do NOT delete local Catch data immediately after synchronisation.

The current `/catches` experience is a local logbook.

A successfully synced Catch remains available locally.

Do not delete photograph blobs merely because R2 upload succeeded unless a separately designed storage-management requirement explicitly introduces safe eviction/caching.

#17 is synchronisation, not local-cache eviction.

---

# Catch list UX

The existing `/catches` page must surface sync state clearly without becoming visually noisy.

Each Catch should show a compact status.

Examples:

```text
✓ Synchronised
Waiting to synchronise
Synchronising…
Sync failed — Retry
```

Use icon + text where useful; do not rely on colour alone.

For Failed:

provide an obvious touch-friendly Retry action.

Do not require the angler to open developer-style diagnostics.

---

# Record Catch saved-state UX

Do not damage the #14 flow.

After saving:

- Catch remains visible
- photograph carousel remains visible
- “Catch saved on this device” remains meaningful
- `Record another catch` remains explicit

Synchronisation status may be shown quietly on the saved state, but:

- do not replace the local-save confirmation with a network spinner
- do not make the angler wait
- do not clear the Catch when sync succeeds
- do not make sync failure look like Catch-save failure

The distinction must remain clear:

```text
Catch saved ✓
Server synchronisation pending/failed
```

is still a successfully recorded Catch.

---

# Error UX

Do not expose technical exception text to the user.

Use compact localised messages.

Example:

```text
Synchronisation failed.
Your catch is still saved on this device.

[ Retry ]
```

French equivalent required.

Detailed technical failure information may go to the existing diagnostics/logging mechanisms.

Do not log sensitive photograph bytes/tokens/precise coordinates unnecessarily.

---

# Diagnostics

Use existing diagnostic/error logging conventions.

Record useful sync failures such as:

- metadata sync failed
- photograph upload failed
- authentication unavailable
- API unavailable
- R2/upload failure

Include safe correlation identifiers such as:

- CatchId
- PhotographId

Do not log:

- access tokens
- raw photograph bytes
- full precise coordinates unless a documented diagnostic reason exists

---

# API/CQRS architecture

Follow current CQRS/project rules.

Production metadata synchronisation should use the existing real Catch server operation where suitable.

Do not create a parallel:

```text
SyncCatchEndpoint
```

that duplicates normal Catch persistence semantics unless there is a concrete architectural need.

Prefer:

```text
PWA synchroniser
→ authenticated Catch client
→ existing production Catch endpoint
→ IMediator
→ handler/service
→ repository
```

Photograph synchronisation follows the established R2/upload architecture from #11, promoted to production Catch.

Handlers do not inject repositories directly where project CQRS rules forbid it.

Use typed errors for expected failure paths.

---

# Server idempotency must be enforced

Client guards are not sufficient.

The server/database must enforce duplicate prevention.

For metadata:

```text
same owner + same CatchId
→ same server Catch
```

For photographs:

```text
same owner + same CatchId + same PhotographId
→ same logical photograph/object
```

Retry races must not result in duplicate server data.

Use DB constraints/upsert semantics/object-key determinism as appropriate.

Do not implement “check then insert” as the sole duplicate protection where concurrent requests can race.

---

# Photograph upload integrity

Successful photograph sync must preserve:

- exact PhotographId
- CatchId
- content type
- expected bytes/object
- order where applicable

Do not re-label MIME types.

The #14 supported-type rules remain:

- JPEG
- PNG
- WebP

Do not add HEIC conversion in #17 unless separately required.

---

# Server metadata success vs photograph success

Persist enough local sync progress that this scenario works:

```text
metadata POST succeeded
client crashes before local "metadata synced" flag is written
```

On retry, the same stable `CatchId` is sent again.

The server idempotently reuses/updates the same Catch.

Likewise, if an R2 upload may have succeeded but the local success flag was not written, retrying the same PhotographId/object key must remain safe.

Design for **at-least-once delivery**, not an unrealistic exactly-once network assumption.

---

# Do not overwrite newer local data accidentally

#17 does NOT implement sophisticated multi-device conflict resolution.

However, the synchroniser must not construct a stale partial object from sync-state data and overwrite fields that exist on the local production Catch.

Always synchronise from the current locally persisted Catch model.

Sync status is metadata about delivery, not a second copy of the Catch.

---

# Database / server changes

Before implementation, inspect the server schema introduced by #14/#15/#16.

Only add migrations that are genuinely necessary.

Possible production needs include photograph/server-sync persistence, but do not invent fields solely because TestCatch had them.

Use expand-only DbUp migrations.

Do not modify historical migrations.

Use real PostgreSQL/Testcontainers for repository/idempotency tests.

---

# IndexedDB model

Extend the existing production Catch IndexedDB representation with synchronisation metadata.

Do not introduce a second local Catch store.

Preserve the existing Catch + photograph records and blobs.

If the schema structure requires a version bump:

- implement a safe IndexedDB upgrade
- preserve existing #14/#15 Catches
- preserve photographs
- preserve locations
- test upgrade from the previous production schema

Existing users' locally saved Catches must not disappear because #17 added sync state.

---

# TestCatch transition

Before implementation, inventory:

- TestCatch synchroniser
- TestCatch metadata client
- connectivity listener
- retry orchestration
- R2 upload client
- photograph upload/object-key logic
- IndexedDB sync fields
- tests
- diagnostics

For each choose:

**REUSE**
**REFACTOR / GENERALISE**
**TEMPORARILY KEEP**
**REMOVE**

Do not delete a proven TestCatch test until equivalent production Catch behaviour is covered.

End-state goal:

```text
production Catch owns production synchronisation
```

---

# Acceptance Criteria

- [ ] **AC1 — offline save remains independent.** Given the device is offline, when an angler saves a production Catch, then the Catch and photographs save locally without API/R2 access and the UI confirms local success.

- [ ] **AC2 — pending state survives restart.** Given a Catch is waiting to synchronise, when the PWA is closed and reopened, then the Catch remains locally available with its synchronisation state.

- [ ] **AC3 — automatic sync after reconnect.** Given an unsynchronised Catch and usable authentication, when connectivity becomes available / the app is subsequently opened online, then metadata and photographs are attempted automatically.

- [ ] **AC4 — metadata identity is idempotent.** Given the same production `CatchId` is synchronised more than once, then only one server Catch exists for that owner.

- [ ] **AC5 — photograph identity is idempotent.** Given the same production `CatchPhotographId` upload is retried, then no duplicate logical photograph or duplicate random R2 object is created.

- [ ] **AC6 — location synchronises with metadata.** Given a Catch has captured location, when metadata synchronisation succeeds, then exact owner location and its privacy metadata are persisted correctly on the server.

- [ ] **AC7 — photograph retry does not erase location.** Given metadata/location already synchronised and a photograph retry occurs, then existing Catch location and visibility remain unchanged.

- [ ] **AC8 — independent photograph retry.** Given three photographs where A/C synchronised and B failed, when Retry succeeds, then only required work for B is retried and the Catch becomes fully Synchronised.

- [ ] **AC9 — overall status is truthful.** A Catch is not shown as Synchronised until metadata and every required photograph are synchronised.

- [ ] **AC10 — failed sync does not lose the Catch.** Given metadata or photograph synchronisation fails, then all Catch metadata, location, photographs and blobs remain safely stored locally.

- [ ] **AC11 — manual retry.** Given a Failed Catch, when the user selects Retry, then a new synchronisation attempt begins without creating duplicates.

- [ ] **AC12 — multiple pending Catches.** Given several offline Catches, when connectivity returns, then each is independently synchronised and one failure does not prevent other Catches completing.

- [ ] **AC13 — no concurrent duplicate attempt.** Given startup/reconnect/manual retry triggers overlap for the same Catch, then the running client does not launch multiple parallel sync orchestrations for that Catch.

- [ ] **AC14 — interrupted sync is recoverable.** Given the PWA closes during Synchronising, when it is reopened, then the Catch becomes retryable and is not permanently stuck.

- [ ] **AC15 — authentication failure is safe.** Given sync cannot authenticate, then the Catch remains local/pending or failed, no data is lost, and synchronisation may continue after authentication returns.

- [ ] **AC16 — current internal user owns server data.** A client cannot synchronise a Catch into another User by spoofing a UserId/OwnerUserId.

- [ ] **AC17 — privacy preserved.** Synchronisation of exact location does not make a private location visible to another user; #16 response-shaping rules remain effective.

- [ ] **AC18 — UI states.** `/catches` clearly presents Waiting, Synchronising, Synchronised and Failed states and provides Retry for failed Catches.

- [ ] **AC19 — waterside UX preserved.** Synchronisation does not block, clear or turn a successful local Catch save into a failure state.

---

# Test requirements

## Web / synchroniser unit tests

Cover:

- newly saved Catch enters appropriate pending state
- offline does not call API/R2
- online trigger discovers pending Catches
- app-start trigger discovers pending Catches
- metadata success then photograph success
- metadata failure stops photograph phase appropriately
- one photograph failure
- independent retry
- retry successful photographs is avoided where progress is known
- overall Catch state derivation
- stale Synchronising recovery
- multiple pending Catches
- one Catch failure does not prevent others
- concurrent trigger/in-flight guard
- authentication failure retains local state
- current Catch save UI remains independent

Dependency assertions required:

- `Received(n)`
- exact `Arg.Is(...)`
- `DidNotReceive()` on denied/skipped paths

Use AwesomeAssertions.

Follow `WhenTesting{Method}` convention.

Unhappy paths first; happy path last where practical.

---

## IndexedDB / JS tests

Cover production Catch, not only TestCatch:

- sync status round-trip
- photograph status round-trip
- app close/reopen
- metadata-succeeded + photograph-failed state survives reopen
- locations survive sync-state updates
- blobs survive failures
- upgrade from the previous production IndexedDB schema if version changes
- stale `Synchronising` can be recovered
- several pending Catches can be enumerated

Do not duplicate Catch data into a separate sync store unless clearly justified.

---

## API tests

Cover:

- authenticated metadata upsert
- retry same CatchId
- same CatchId does not create duplicate
- spoofed UserId cannot change ownership
- exact location persists
- visibility persists
- private location remains privacy-shaped under #16 reads
- appropriate authentication failure
- expected server errors remain typed/mapped correctly

---

## Infrastructure / Testcontainers

Use real PostgreSQL for:

- Catch upsert idempotency
- same client CatchId retry
- ownership isolation
- exact location/visibility round-trip
- photograph record idempotency where persisted in DB
- uniqueness constraints
- retry does not erase metadata/location
- multiple photographs on one Catch

Do not replace repository integration tests with mocks.

---

## R2 / photograph tests

At the appropriate abstraction level prove:

- stable deterministic Photograph identity/object key
- retry is safe
- successful photo is not logically duplicated
- content type remains correct
- one failed photo does not invalidate other successful photos
- photo retry does not send a partial Catch update that erases location

Use a fake/test storage boundary where appropriate; do not require live production R2 for normal CI.

---

## Browser assessment

Assess real browser coverage under `self-review.md`.

Use the existing JS/Playwright harness where it genuinely proves:

- IndexedDB persistence
- online/offline event orchestration
- close/reopen state

Do NOT reintroduce test authentication into production Web.

Do NOT resurrect the #76 authenticated-Blazor-host problem solely for #17.

API/integration/unit tests prove authenticated server behaviour.

---

# Localisation

All new user-visible sync copy requires EN/FR.

At minimum:

- Saved on this device
- Waiting to synchronise
- Synchronising
- Synchronised
- Synchronisation failed
- Retry
- Catch remains saved on this device / equivalent failure reassurance where shown

Do not store localised labels as sync-state values.

---

# Self-review

The PR must run the normal mandatory self-review and explicitly answer:

### Product

- Can an angler still save instantly while offline?
- Does sync failure ever look like Catch-save failure?
- Can the user see what is pending/failed?
- Is Retry obvious and touch-friendly?

### Data integrity

- Can the same Catch be created twice?
- Can the same Photograph be created/uploaded twice?
- Can photograph retry erase location?
- Can sync status updates erase Catch data?
- Can app close/reopen lose progress?
- Can a Catch get stuck forever in Synchronising?

### Security

- Can client-supplied UserId alter ownership?
- Is `ICurrentUser` authoritative?
- Does sync weaken #16 privacy?
- Are tokens/precise coordinates unnecessarily logged?

### Architecture

- Did we reuse/generalise TestCatch proof rather than create parallel synchronisers?
- Is sync state delivery metadata rather than a second Catch model?
- Are CQRS/service/repository boundaries followed?
- Is API idempotency enforced server-side, not merely in the browser?

### Testing

- Are dependency calls asserted with exact inputs?
- Are negative paths covered?
- Is multi-photo partial failure covered?
- Is location retained across photograph retry?
- Is restart/interruption covered?
- Are real PostgreSQL constraints tested?
- Is browser coverage assessed rather than assumed?

---

# Out of scope

Do NOT add:

- sophisticated simultaneous multi-device edit conflict resolution
- merge conflict UI
- Catch editing (#19)
- full Catch History/filtering (#20)
- FishingVenue association (#27)
- explicit precise-location sharing with selected users
- competition verification exceptions
- background GPS tracking
- background photograph capture
- native mobile background services
- HEIC conversion
- automatic local-cache eviction after sync
- AI species identification
- true guaranteed sync while the iOS PWA is fully terminated

#17 owns reliable eventual production Catch synchronisation while the PWA is running/opened and provides clear retryable state when delivery cannot complete.

---

# Definition of Done

- [ ] All Acceptance Criteria satisfied
- [ ] Production Catch is the active synchronisation path
- [ ] Catch metadata retry is idempotent
- [ ] Photograph retry is idempotent
- [ ] Location is preserved through all retry paths
- [ ] #16 location privacy remains intact
- [ ] Sync states survive close/reopen
- [ ] Failed sync can be manually retried
- [ ] Multiple pending Catches work independently
- [ ] Offline Catch Save remains network-independent
- [ ] TestCatch synchronisation inventory completed
- [ ] Equivalent production tests exist before obsolete TestCatch tests are removed
- [ ] Automated tests added and passing
- [ ] Dependency calls asserted according to testing rules
- [ ] Real PostgreSQL integration coverage added where persistence changes
- [ ] Browser coverage assessed
- [ ] User-visible text localised EN/FR
- [ ] Mandatory self-review completed
- [ ] No unrelated scope added

### PR DESCRIPTION
**Pull request by kingkeamo**
## Summary
- Makes production Catch the active synchronised path: local IndexedDB save stays offline-first, then metadata and photographs sync afterwards using the existing Catch API, deterministic R2 object keys, and owner identity from `ICurrentUser`.
- Persists Catch and photograph sync state, recovers stale `Synchronising` after restart, retries outstanding work only, and shows compact status plus Retry on `/catches` (EN/FR).
- Fixes the live sync 503: Npgsql cannot write `DateTimeOffset` with a non-UTC offset, so Catch timestamps are normalised to UTC at persistence. Server-side catch blocks now log the original exception instead of swallowing it.

Closes #17.

## TestCatch inventory
| Area | Decision |
|---|---|
| Metadata upsert / idempotent CatchId | REFACTOR / GENERALISE into production `CatchClient` + `CatchSynchroniser` |
| Photograph upload URL + R2 PUT + record | REFACTOR / GENERALISE; object key is deterministic `catches/{userId}/{catchId}/{photographId}` |
| In-flight per-catch guard, retry, startup/reconnect | REFACTOR / GENERALISE; MainLayout `online` / `pageshow` / visibility triggers |
| IndexedDB sync fields | REUSE production Catch store; merge sync metadata without overwriting newer local location/privacy |
| Ownership | REUSE #16: local UserId scopes which Catches may sync; server ownership is `ICurrentUser` only |
| Diagnostics | REUSE bounded client diagnostic logger and a small #17 event set only; do not promote verbose TestCatch tracing |
| `/test-catch` route | REMOVE from user-facing navigation; TestCatch proof code/tests kept until production coverage exists |

## Not in this PR
- Catch editing (#19)
- Catch history/filtering (#20)
- FishingVenue association (#27)
- Multi-device conflict UI
- Authenticated Playwright host (#76)
- True iOS background sync while the PWA is terminated

## Test plan
- [x] Targeted repository/upsert tests for non-UTC `CaughtOn` / `CapturedOn`
- [x] Targeted RecordCatch save tests (`CaughtOn` offset is UTC)
- [x] Targeted exception-logging tests (Catch upsert, identity unique recovery, capability FK, TestCatch photograph mismatch)
- [ ] CI green on this PR
- [ ] Record a Catch on a non-UTC machine, confirm local save, then confirm metadata sync is 200 not 503
- [ ] Confirm Failed still shows Retry and the Catch remains on the device
- [ ] Confirm a User A Catch does not sync while User B is signed in

## Self review
- Issue/AC: PASS for the implemented sync path (AC1–AC19 in code/tests). Manual UTC+4 sync originally failed with 503; that is fixed in this branch.
- Architecture/CQRS: PASS (PWA synchroniser → Catch client → existing Catch endpoints → mediator → service → repository). No parallel SyncCatch endpoint.
- Offline-first: PASS — Record Catch still finishes at IndexedDB; sync is later/best-effort.
- Idempotency: PASS — stable CatchId / PhotographId; deterministic object keys; upsert on conflict.
- Security/privacy: PASS — server UserId from `ICurrentUser`; #16 viewer shaping unchanged; exact owner coordinates still persist for the owner.
- Diagnostics: PASS — small event set; sync state is not driven by diagnostics; catch blocks log exceptions server-side without returning them to clients.
- Tests: PASS for added unit/API/Testcontainers/bUnit coverage. Browser IndexedDB close/reopen is covered where the existing harness can without production test auth.
- Extra scope: server-side exception-logging rule is included because silent repository catches hid the UTC sync failure. Web client catch blocks are not in this rule.
- CI/deployment: no new DbUp migration. Restart API after pull so UTC normalisation and logging are loaded.

### CODE REVIEW

**Review by kingkeamo — COMMENTED** [review]
Initial review of #82: the core sync architecture is directionally good — production Catch has persisted metadata/photo sync state, owner-scoped local reads, deterministic photograph keys, stale `Synchronising` recovery, per-Catch in-flight protection, targeted retry, UTC normalisation at the persistence boundary, and the new server-side exception logging rule addresses the observability gap that hid the live Npgsql failure.

I found one user-visible orchestration blocker before merge:

### A newly saved Catch does not start synchronising while the angler remains on Record Catch

`MainLayout` triggers `SynchronisePendingAsync()` on first render, navigation/location change, browser `online`, and `pageshow`/visibility usability events. However `RecordCatch.SaveAsync()` only persists the Catch to `ICatchStore` and marks `_isSaved = true`; it never signals the synchroniser.

Because #14 deliberately keeps the saved Catch on the Record Catch screen, the common online flow is now:

1. app/layout starts while online and scans pending work (none yet)
2. angler opens Record Catch
3. angler taps Save
4. Catch is safely persisted locally
5. angler stays on the same page
6. no navigation, no new `online` event, no `pageshow` event occurs
7. Catch remains `SavedLocally` until some later navigation/re-entry event

That is not the behaviour we want for #17. Local Save must still complete at IndexedDB and never wait for the network, but after local persistence succeeds it should **best-effort trigger production synchronisation immediately**. The trigger must be fire-and-forget/non-blocking from the waterside Save perspective: sync/API/R2 failure must not change `_isSaved` or turn the local save into an error.

Please add the smallest clean mechanism to notify/start `ICatchSynchroniser` after local Save succeeds, without coupling Save completion to network completion. Add focused tests proving:

- local `CatchStore.SaveAsync` completes before sync is triggered
- successful local save triggers one production sync opportunity while remaining on Record Catch
- sync failure/unavailable network does not make Record Catch show Save failed
- local store failure does not trigger sync

The current Record Catch UI always displays `SavedLocally`; it does not need to become a full live sync-status UI in this fix unless required by the existing #17 UX, but the actual background synchronisation must start.

CI for head `efa8a375` is currently still running, so this review is not a merge approval yet.

**Review by kingkeamo — COMMENTED** [review]
Re-review of head `70636f58`: the previous Record Catch orchestration finding is functionally addressed. Local persistence completes first, successful save triggers one best-effort `ICatchSynchroniser.SynchronisePendingAsync()` call without awaiting it from the waterside save path, local-store failure does not trigger sync, and sync failure does not turn the saved Catch into a Save failure. The focused bUnit coverage covers those cases, and CI is green.

One observability issue remains in the new fix before I would call #82 ready for final device testing:

### `SafeSynchronisePendingAsync` silently swallows unexpected synchroniser exceptions

The newly added method has:

```csharp
catch (Exception)
{
}
```

`CatchSynchroniser` already handles normal metadata/photo/network failures internally and records their sync state/diagnostics. An exception that escapes `SynchronisePendingAsync` is therefore an unexpected orchestration/store/auth/diagnostic failure. Swallowing it here recreates the exact debugging gap we have just been correcting: e.g. an IndexedDB/read failure before an individual Catch enters its internal sync try/catch would disappear completely.

Please keep the fire-and-forget/non-blocking behaviour, but log the escaped exception through the existing Web `ILoggingService` (the same pattern `MainLayout.SynchroniseAsync` already uses). Request-abort/dispose cancellation can remain quiet. Add a focused test that a thrown unexpected synchroniser exception does not affect local Save success **and** is passed to the logging path.

This is a small change; I found no new ownership/privacy/idempotency blocker in this follow-up commit.
